version: '3.8'
services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        volumes:
            - ./logs:/usr/src/app/logs
            - ./logs.langchain:/usr/src/app/logs.langchain
        networks:
            - api-network
        restart: always
        depends_on:
            - redis
    redis:
        image: redis:6.0.20
        ports:
            - 6379:6379
        networks:
            - api-network
        volumes:
            - ./data/redis:/data
        restart: always
networks:
    api-network:
        driver: bridge
